platform:ios,’10.0’
use_frameworks!

flutter_application_path = '../my_flutter/'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'Flutter_iOS' do

  install_all_flutter_pods(flutter_application_path)
end

